{
 "title": "my - dashboard ",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "histogram",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(request_duration_seconds_bucket{exported_endpoint!=\"/metrics\", exported_endpoint!=\"login\"}[1m])) by (le, exported_endpoint))\n",
     "legendFormat": "p50-{{exported_endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(request_duration_seconds_bucket{exported_endpoint!=\"/metrics\"}[1m])) by (le, exported_endpoint))\n",
     "legendFormat": "p90-{{exported_endpoint}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket{exported_endpoint!=\"/metrics\"}[1m])) by (le, exported_endpoint))\n",
     "legendFormat": "p99-{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "server calls per minute, by endpoint",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(request_total{endpoint!=\"metrics\", exported_endpoint!=\"login\"}[1m])) by (exported_endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(request_processing_seconds_sum{exported_endpoint!=\"metrics\", exported_endpoint!=\"login\"}[1m])/increase(request_processing_seconds_count{exported_endpoint!=\"metrics\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}