# Default values for myapp.
replicaCount: 1


kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelector:
        matchLabels:
          release: prometheus

grafana:
  dashboardsConfigMaps:
    default: grafana-dashboard-custom