apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.ports.servicePort }}
      targetPort: {{ .Values.postgres.ports.containerPort }}
  selector:
    app: {{ .Values.postgres.name }}
  clusterIP: None  # Headless service
