apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.flaskApp.name }}
spec:
  replicas: {{ .Values.flaskApp.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.flaskApp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.flaskApp.name }}
    spec:
      containers:
      - name: {{ .Values.flaskApp.name }}
        image: "{{ .Values.flaskApp.image.repository }}:{{ .Values.flaskApp.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.flaskApp.image.pullPolicy | default "IfNotPresent" }}
        ports:
        - containerPort: {{ .Values.flaskApp.ports.containerPort }}
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.user }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgres.password.secretName }}
              key: {{ .Values.postgres.password.secretKey }}
        - name: DB_HOST
          value: {{ .Values.flaskApp.dbHost }}
        - name: POSTGRES_PORT
          value: "{{ .Values.flaskApp.dbPort }}"
        - name: POSTGRES_DB
          value: {{ .Values.postgres.db }}
        - name: POSTGRES_OPTIONS
          value: "{{ .Values.flaskApp.dbOptions }}"
